name: Example - Validate and Publish OpenAPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: flipdishbytes/publish-api@main
    with:
      openapi_file_path: 'example/openapi.json'
      readme_version: 'v3.0'
      skip_readme_publish: false
    secrets:
      README_API_KEY: ${{ secrets.README_API_KEY_TEST }} 